const Task = require('../models/Task');
const { deleteImage } = require('../middleware/multer');

// @desc    Create a new task with WebP attachments
// @route   POST /api/tasks
// @access  Public / Admin
exports.createTask = async (req, res) => {
  try {
    const { name, project, assignees, priority, status, date, progress, description } = req.body;

    // Parse assignees if sent as a JSON string via FormData
    let parsedAssignees = assignees;
    if (typeof assignees === 'string') {
      try {
        parsedAssignees = JSON.parse(assignees);
      } catch (e) {
        parsedAssignees = [assignees];
      }
    }

    if (!name || !project || !date || !parsedAssignees || parsedAssignees.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'Please fill in all mandatory fields, including assignees.',
      });
    }

    // Process attachments generated by Sharp middleware
    let attachments = [];
    if (req.uploadedImages && req.uploadedImages.length > 0) {
      attachments = req.uploadedImages.map((img) => ({
        name: img.filename,
        url: img.path, // relative path: /uploads/timestamp-random.webp
        fileType: 'image/webp',
      }));
    }

    const newTask = await Task.create({
      name,
      project,
      assignees: parsedAssignees,
      priority,
      status,
      date,
      progress,
      description,
      attachments,
      createdBy: req.employee ? req.employee._id : null,
    });

    const populatedTask = await Task.findById(newTask._id).populate(
      'assignees',
      'name employeeId email'
    );

    res.status(201).json({
      success: true,
      data: populatedTask,
      message: 'Task created and assigned successfully.',
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Get all tasks
// @route   GET /api/tasks
// @access  Public / Unprotected
exports.getAllTasks = async (req, res) => {
  try {
    let query = {};

    if (req.employee && req.employee.role !== 'Admin' && req.employee.role !== 'admin') {
      query = { assignees: req.employee._id };
    }

    const tasks = await Task.find(query)
      .populate('assignees', 'name employeeId email avatar')
      .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      count: tasks.length,
      data: tasks,
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Get current employee tasks
// @route   GET /api/tasks/my-tasks
// @access  Private
exports.getMyTasks = async (req, res) => {
  try {
    const employeeId = req.employee._id;

    const myTasks = await Task.find({ assignees: employeeId })
      .populate('assignees', 'name employeeId email avatar')
      .sort({ date: 1 });

    res.status(200).json({
      success: true,
      count: myTasks.length,
      data: myTasks,
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Update task details or upload additional WebP attachments
// @route   PUT /api/tasks/:id
// @access  Public / Optional Auth
exports.updateTask = async (req, res) => {
  try {
    let task = await Task.findById(req.params.id);

    if (!task) {
      return res.status(404).json({ success: false, message: 'Task not found' });
    }

    let updateData = { ...req.body };

    // Prevent direct string/object override of attachments array from body
    delete updateData.attachments;

    // Parse assignees if sent as a JSON string via FormData
    if (typeof updateData.assignees === 'string') {
      try {
        updateData.assignees = JSON.parse(updateData.assignees);
      } catch (e) {
        updateData.assignees = [updateData.assignees];
      }
    }

    // Append notes if supplied
    if (updateData.newNote) {
      const noteObj = {
        author: (req.employee && req.employee.name) || updateData.noteAuthor || 'Manager',
        message: updateData.newNote,
        timestamp: new Date(),
      };
      updateData.notes = [noteObj, ...(task.notes || [])];
      delete updateData.newNote;
    }

    // Preserve existing attachments already in database
    let existingAttachments = task.attachments || [];

    // Append newly uploaded images transformed to WebP
    if (req.uploadedImages && req.uploadedImages.length > 0) {
      const newAttachments = req.uploadedImages.map((img) => ({
        name: img.filename,
        url: img.path,
        fileType: 'image/webp',
      }));
      updateData.attachments = [...existingAttachments, ...newAttachments];
    } else {
      updateData.attachments = existingAttachments;
    }

    task = await Task.findByIdAndUpdate(req.params.id, updateData, {
      new: true,
      runValidators: true,
    }).populate('assignees', 'name employeeId email avatar');

    res.status(200).json({
      success: true,
      data: task,
      message: 'Task updated successfully',
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Delete Task & purge image files from server disk
// @route   DELETE /api/tasks/:id
// @access  Public / Unprotected
exports.deleteTask = async (req, res) => {
  try {
    const task = await Task.findById(req.params.id);

    if (!task) {
      return res.status(404).json({ success: false, message: 'Task not found' });
    }

    if (req.employee) {
      const userIdStr = req.employee._id.toString();
      const isAssigned = task.assignees.some((id) => id.toString() === userIdStr);
      const isAdmin = req.employee.role === 'Admin' || req.employee.role === 'admin';

      if (!isAssigned && !isAdmin) {
        return res.status(403).json({
          success: false,
          message: 'Forbidden: You are not authorized to delete this task.',
        });
      }
    }

    // Delete physically stored image files from disk
    if (task.attachments && task.attachments.length > 0) {
      task.attachments.forEach((att) => {
        if (att.name) {
          deleteImage(att.name);
        }
      });
    }

    await task.deleteOne();

    res.status(200).json({
      success: true,
      message: 'Task and attachments deleted successfully',
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};