import React from 'react';
import { LuCalendarDays } from 'react-icons/lu';
import { LuFileText } from 'react-icons/lu';
import { AiFillStar, AiOutlineStar } from 'react-icons/ai';
import { BiLike, BiDislike } from 'react-icons/bi';
import './Invoices.css';

const Invoices = () => {
  // Mock data matching the exact records in the image
  const invoiceData = [
    { id: 1, invoiceNo: "#IN7865", avatar: "https://i.pravatar.cc/150?img=32", name: "John Doe", date: "12/05/2016", status: "Paid", total: "$500" },
    { id: 2, invoiceNo: "#IN2301", avatar: "https://i.pravatar.cc/150?img=12", name: "Sarah Smith", date: "03/31/2016", status: "Not Paid", total: "$372" },
    { id: 3, invoiceNo: "#IN7239", avatar: "https://i.pravatar.cc/150?img=47", name: "Airi Satou", date: "04/14/2017", status: "Partially Paid", total: "$1038" },
    { id: 4, invoiceNo: "#IN1482", avatar: "https://i.pravatar.cc/150?img=44", name: "Angelica Ra...", date: "08/11/2017", status: "Paid", total: "$872" },
    { id: 5, invoiceNo: "#IN8526", avatar: "https://i.pravatar.cc/150?img=60", name: "Ashton Cox", date: "02/15/2018", status: "Not Paid", total: "$2398" },
    { id: 6, invoiceNo: "#IN2473", avatar: "https://i.pravatar.cc/150?img=45", name: "Cara Stevens", date: "01/28/2017", status: "Paid", total: "$834" },
    { id: 7, invoiceNo: "#IN7366", avatar: "https://i.pravatar.cc/150?img=68", name: "Jacob Ryan", date: "03/11/2017", status: "Partially Paid", total: "$147" }
  ];

  const reviewData = [
    {
      id: 1,
      avatar: "https://i.pravatar.cc/150?img=32",
      name: "Alis Smith",
      time: "a week ago",
      rating: 3,
      comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam vel rutrum ex, at ornare mi. In quis scelerisque dui, eget rhoncus orci. Fusce et sodales ipsum. Nam id nunc euismod, aliquet arcu quis, mattis nisi."
    },
    {
      id: 2,
      avatar: "https://i.pravatar.cc/150?img=12",
      name: "John Dio",
      time: "a week ago",
      rating: 2,
      comment: "Nam quis ligula est. Nunc sed risus non turpis tristique tempor. Ut sollicitudin faucibus magna nec gravida. Suspendisse ullamcorper justo vel porta imperdiet. Nunc nec ipsum vel augue placerat faucibus."
    }
  ];

  const renderStars = (rating) => {
    const stars = [];
    for (let i = 1; i <= 5; i++) {
      if (i <= rating) {
        stars.push(<AiFillStar key={i} className="Invoices-star-filled" />);
      } else {
        stars.push(<AiOutlineStar key={i} className="Invoices-star-empty" />);
      }
    }
    return stars;
  };

  const getStatusClassName = (status) => {
    return `Invoices-status-badge status-${status.toLowerCase().replace(' ', '-')}`;
  };

  return (
    <div className="Invoices-container">
      {/* Left Column: Invoices Table */}
      <div className="Invoices-table-card">
        <div className="Invoices-card-header">
          <h2>Invoices</h2>
          <button className="Invoices-view-all-btn">View All</button>
        </div>

        <div className="Invoices-table-wrapper">
          <table className="Invoices-table">
            <thead>
              <tr>
                <th>Invoice No</th>
                <th>Generated By</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Total</th>
                <th className="Invoices-text-center">Download</th>
              </tr>
            </thead>
            <tbody>
              {invoiceData.map((invoice) => (
                <tr key={invoice.id}>
                  <td className="Invoices-number-text">{invoice.invoiceNo}</td>
                  <td>
                    <div className="Invoices-user-cell">
                      <img src={invoice.avatar} alt={invoice.name} className="Invoices-avatar-img" />
                      <span className="Invoices-name-text">{invoice.name}</span>
                    </div>
                  </td>
                  <td>
                    <div className="Invoices-date-cell">
                      <LuCalendarDays className="Invoices-calendar-icon" />
                      <span>{invoice.date}</span>
                    </div>
                  </td>
                  <td>
                    <span className={getStatusClassName(invoice.status)}>
                      {invoice.status}
                    </span>
                  </td>
                  <td className="Invoices-total-text">{invoice.total}</td>
                  <td>
                    <div className="Invoices-download-action">
                      <button className="Invoices-download-btn" title="Download Document">
                        <LuFileText />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Right Column: Customer Review */}
      <div className="Invoices-review-card">
        <div className="Invoices-card-header">
          <h2>Customer Review</h2>
          <button className="Invoices-view-all-btn">View All</button>
        </div>

        <div className="Invoices-reviews-list">
          {reviewData.map((review) => (
            <div key={review.id} className="Invoices-review-item">
              <div className="Invoices-review-user-row">
                <img src={review.avatar} alt={review.name} className="Invoices-review-avatar" />
                <div className="Invoices-review-meta">
                  <span className="Invoices-review-username">{review.name}</span>
                  <span className="Invoices-review-time">{review.time}</span>
                </div>
              </div>
              
              <div className="Invoices-rating-row">
                {renderStars(review.rating)}
              </div>

              <p className="Invoices-review-text">{review.comment}</p>

              <div className="Invoices-review-actions">
                <button className="Invoices-reaction-btn like"><BiLike /></button>
                <button className="Invoices-reaction-btn dislike"><BiDislike /></button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Invoices;